language: bash
services:
- docker
before_install:
- docker login --username "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_PASSWORD"
- docker search "$DOCKER_HUB_USERNAME"
- env | sort
script:
- travis_retry ./script.sh
after_script:
- docker images
after_success:
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::6}
  - secure: X0zpr2Fd5pJqciC9JwXZxYcYmGLcX00mdAasS/Kh8nPOd8f0AaIMk23ZbAXE6UEBvVnlzQaUOpw+JgNbCQqTn9nLQbpWtL2VwcH7jaqSoc1SXFaef97pwq35mvtxJ6wg/WKaUnmYzUjSbdIZqky0pGI2OiWPQUBv1TpteHFX14eZL7WBjd/x5WSFAfpBZ678zdszl6JeUEpOGUl/cGqCbaFmZwxzLJ8ay1vKZT8IWLnAV51Ntg6fQrpJp6xZR+qyjezUPv8wkjAQAhtqPzqzpZ6N/7yKiHskwfg3ihq+d8CmQp4pzwqIy/uS/QAf9b8XFHDER2+2l7C0fGan45FizUjYoEJ1KuOKbNoew/ZjjtsSjaoH8tZzAm0HI2JpWsd9pxoKN0k35cPCLQxTXFa80on/k3N5rMcAABUbiWfGhjmoI5dkvcEzOiIxzxQGby164512w5ULSAlBXdAEACBW6DnN9k8FKQHa4r7Ed+QMO8WY2hCPACK0+dOjvwt2w0TZX4nIsiDWCNGy4F8+MGQuSiwkpYhhAXbovbDx1jFYWjh2EIjTKtWyCNvqlQ/dG4DNjNlAW2dbmIRm7iwTMMwPDR/wmNvLPIm5ifyU3Nrs2Dz4mWJLTVI1oQXHKY38VMLi48iLcf2gznUt4z85sWYsyEYuJn9uhzbM4OwPyiikxE0=
  - secure: UgUrUxAwLIzugdaqXOQT5jMQmnSfsOWq0VerFiUdkGlgY1UTqaAWPtnktAqkicYB2Vf1UtFNs095Or2muYMMbWfYW85F8puulESzNi2lXPB03VolqyBKbZGf+StIual/mfyJOKocPfe6sy1a/mD49xMRm/3e2jM11h+BbN1ot0ub/hgCuk4c/8pWz0WPfSqOOyrReiaj7MC6wMI5zy2qPal12h+vYiQ38cbgawcY9jNY4wTCFHfut4whI25cyDWr7jTjhQZJCIHVW5Ii1bBKfjxPK/+y6idQcc70lYajsRaagCJ3uD4V+oXxAaUTeWlGxZvct5CpjhPxBbNz2M3SO149K9lgQM0sn2D5gJGKrzh4PBB0rankVP+L2eUi1rgTHX8pY1jrBTl6qO9zEQV7tcR+LT9ZSvieKLRGyMU40mpfYYOSaHaiY+wUUYvpfSBasWWU+yF6m3ZPoxjT+eVE8+3FbQqyZNaz9mqM8JnZpn9RgPaQLx8ypBCRpZGCCJc4r6WWnpPFzI+W1f80E7srxt9Cd9KCJOBPd6oc47aEadxw41o+ZAmIOCu2/7YWur5e93gBM6A0IaVZ6IDyN3psIia84hfRVA2oS4hn1DgQmNseyPe3K403NrqLnrNP2dCtfDTMyzdlHVzJoPcSVndOQK+Dfy0laqApX7lKyqJlLME=
  matrix:
  - ADIR=alpine TAG=3.7 LATEST=y
  - ADIR=alpine TAG=3.7 VARIANT=openssh

  - ADIR=emacs TAG=25.3-r0 LATEST=y

  # - ADIR=debian TAG=jessie
  # - ADIR=debian TAG=jessie-slim
  # - ADIR=debian TAG=stable
  # - ADIR=debian TAG=stable-slim
  # - ADIR=debian TAG=stretch
  # - ADIR=debian TAG=stretch-slim

  - ADIR=oraclejdk TAG=8-jre TAGS="8 8u162 8u162-jre" LATEST=y # require debian:stable
  - ADIR=oraclejdk TAG=8-jre TAGS="8 8u162 8u162-jre" VARIANT=slim # require debian:stable-slim
  - ADIR=oraclejdk TAG=8-jre TAGS="8 8u162 8u162-jre" VARIANT=alpine # require alpine

  - ADIR=openjdk TAG=8-jre TAGS="8 8u151 8u151-jre" LATEST=y # require debian:stable
  - ADIR=openjdk TAG=8-jre TAGS="8 8u151 8u151-jre" VARIANT=slim # require debian:stable-slim
  - ADIR=openjdk TAG=8-jre TAGS="8 8u151 8u151-jre" VARIANT=alpine # require debian:stable-slim

  - ADIR=boot-clj TAG=oracle-8-jre  TAGS="oracle-8 oracle-8u152"                 TAG_PREFIX=2.7.2 BUILD_ARGS="--build-arg BOOT_VERSION=2.7.2 --build-arg BOOT_CHECKSUM=f717ef381f2863a4cad47bf0dcc61e923b3d2afb"
  - ADIR=boot-clj TAG=oracle-8-jre  TAGS="oracle-8 oracle-8u152"  VARIANT=slim   TAG_PREFIX=2.7.2 BUILD_ARGS="--build-arg BOOT_VERSION=2.7.2 --build-arg BOOT_CHECKSUM=f717ef381f2863a4cad47bf0dcc61e923b3d2afb"
  - ADIR=boot-clj TAG=openjdk-8-jre TAGS="openjdk-8 openjdk-8u151"                TAG_PREFIX=2.7.2 BUILD_ARGS="--build-arg BOOT_VERSION=2.7.2 --build-arg BOOT_CHECKSUM=f717ef381f2863a4cad47bf0dcc61e923b3d2afb"
  - ADIR=boot-clj TAG=openjdk-8-jre TAGS="openjdk-8 openjdk-8u151" VARIANT=slim   TAG_PREFIX=2.7.2 BUILD_ARGS="--build-arg BOOT_VERSION=2.7.2 --build-arg BOOT_CHECKSUM=f717ef381f2863a4cad47bf0dcc61e923b3d2afb"
  - ADIR=boot-clj TAG=openjdk-8-jre TAGS="openjdk-8 openjdk-8u151" VARIANT=alpine TAG_PREFIX=2.7.2 BUILD_ARGS="--build-arg BOOT_VERSION=2.7.2 --build-arg BOOT_CHECKSUM=f717ef381f2863a4cad47bf0dcc61e923b3d2afb"

  - ADIR=lein TAG=oracle-8-jre  TAGS="oracle-8 oracle-8u152"                TAG_PREFIX=2.7.1 BUILD_ARGS="--build-arg LEIN_VERSION=2.7.1"
  - ADIR=lein TAG=oracle-8-jre  TAGS="oracle-8 oracle-8u152"   VARIANT=slim TAG_PREFIX=2.7.1 BUILD_ARGS="--build-arg LEIN_VERSION=2.7.1"
  - ADIR=lein TAG=openjdk-8-jre TAGS="openjdk-8 openjdk-8u151"              TAG_PREFIX=2.7.1 BUILD_ARGS="--build-arg LEIN_VERSION=2.7.1"
  - ADIR=lein TAG=openjdk-8-jre TAGS="openjdk-8 openjdk-8u151" VARIANT=slim TAG_PREFIX=2.7.1 BUILD_ARGS="--build-arg LEIN_VERSION=2.7.1"

notifications:
  slack:
    rooms:
    - secure: yGzvUZUD8YZ4yPtWth1ynbQ25voXbdKnOnOPSRt59n3aLdSoOt1jVU6ZQUTZ26Eb5hW9z5tqFtrh1tBCJpJkWDGdLJnJRaNa6Si01E17aICxL11uXEK0sahOj3L8/jQIXrSFJKGr75460q33B4aO1l0zGCHsWGL1Kcs+ZqyxeR5afmX4OghpvmyAvHbl9k4ugXdTIbMLwv01qm0HYvJcCzLqU07pY35hN/xPIP1xmt5syFE6jSLfHXKKQk++JcT+JnpMXpmSAuDGBh5fDs6eya5rfx7zuDllooRQ2tXVh1PTyJkfH6ggnPH4U5Tj+ENLseOaWR0emf8cmFAwbUa2Ebg4Z0jM9uaFnKfPw53eIdkQqQq/jlzBuNQ3PwilwdJBYR8X0kVTjDgW2IPLxuiIFW5yPbDG/Ys5rNyhvi92ujjy8pNJzGaZJp8tF4sBxNMB/Ycx1l11CMbAy8q+SJsmAgdXfSFBOj/bgSOd1F97jXhkAOJ9N4bq/0ZeXvVnLRMQ5uZnMuEpsDqBkt+izFl283lnyKcrLXwQ7JDQtAloH5EpXTu40QoJT2k8Y+9MkQSAhlRAQsZuh3BWo+N40Llaeh+YBGMg245r2jgzA7isz9mt6nnrg0DT3RwCC0kbPDn6o7TCnMpceJgqfRyKXE4dnkQYqVrCtj3uIo5TqtCPtWY=
    on_success: always
    on_failure: always
