language: bash


services:
  - docker


before_install:
  - docker login --username "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_PASSWORD"
  - docker search "$DOCKER_HUB_USERNAME"
  - env | sort


script: travis_retry ./script.sh


after_success:
  - docker images


env:
  global:
    - COMMIT=${TRAVIS_COMMIT::6}
    - secure: X0zpr2Fd5pJqciC9JwXZxYcYmGLcX00mdAasS/Kh8nPOd8f0AaIMk23ZbAXE6UEBvVnlzQaUOpw+JgNbCQqTn9nLQbpWtL2VwcH7jaqSoc1SXFaef97pwq35mvtxJ6wg/WKaUnmYzUjSbdIZqky0pGI2OiWPQUBv1TpteHFX14eZL7WBjd/x5WSFAfpBZ678zdszl6JeUEpOGUl/cGqCbaFmZwxzLJ8ay1vKZT8IWLnAV51Ntg6fQrpJp6xZR+qyjezUPv8wkjAQAhtqPzqzpZ6N/7yKiHskwfg3ihq+d8CmQp4pzwqIy/uS/QAf9b8XFHDER2+2l7C0fGan45FizUjYoEJ1KuOKbNoew/ZjjtsSjaoH8tZzAm0HI2JpWsd9pxoKN0k35cPCLQxTXFa80on/k3N5rMcAABUbiWfGhjmoI5dkvcEzOiIxzxQGby164512w5ULSAlBXdAEACBW6DnN9k8FKQHa4r7Ed+QMO8WY2hCPACK0+dOjvwt2w0TZX4nIsiDWCNGy4F8+MGQuSiwkpYhhAXbovbDx1jFYWjh2EIjTKtWyCNvqlQ/dG4DNjNlAW2dbmIRm7iwTMMwPDR/wmNvLPIm5ifyU3Nrs2Dz4mWJLTVI1oQXHKY38VMLi48iLcf2gznUt4z85sWYsyEYuJn9uhzbM4OwPyiikxE0=
    - secure: UgUrUxAwLIzugdaqXOQT5jMQmnSfsOWq0VerFiUdkGlgY1UTqaAWPtnktAqkicYB2Vf1UtFNs095Or2muYMMbWfYW85F8puulESzNi2lXPB03VolqyBKbZGf+StIual/mfyJOKocPfe6sy1a/mD49xMRm/3e2jM11h+BbN1ot0ub/hgCuk4c/8pWz0WPfSqOOyrReiaj7MC6wMI5zy2qPal12h+vYiQ38cbgawcY9jNY4wTCFHfut4whI25cyDWr7jTjhQZJCIHVW5Ii1bBKfjxPK/+y6idQcc70lYajsRaagCJ3uD4V+oXxAaUTeWlGxZvct5CpjhPxBbNz2M3SO149K9lgQM0sn2D5gJGKrzh4PBB0rankVP+L2eUi1rgTHX8pY1jrBTl6qO9zEQV7tcR+LT9ZSvieKLRGyMU40mpfYYOSaHaiY+wUUYvpfSBasWWU+yF6m3ZPoxjT+eVE8+3FbQqyZNaz9mqM8JnZpn9RgPaQLx8ypBCRpZGCCJc4r6WWnpPFzI+W1f80E7srxt9Cd9KCJOBPd6oc47aEadxw41o+ZAmIOCu2/7YWur5e93gBM6A0IaVZ6IDyN3psIia84hfRVA2oS4hn1DgQmNseyPe3K403NrqLnrNP2dCtfDTMyzdlHVzJoPcSVndOQK+Dfy0laqApX7lKyqJlLME=
  matrix:
    # - ADIR=alpine TAG=3.11 LATEST=y
    # - ADIR=alpine TAG=3.11 VARIANT=openssh


    # - ADIR=alpine-glibc TAG=3.8


    - ADIR=emacs TAG=26.3 LATEST=y
    - REPO=ajchemist/emacs DOCKERFILE_PATH=emacs/26.3-org-mind-map TAGS="org-mind-map 26.3-org-mind-map"


    # - ADIR=debian TAG=jessie
    # - ADIR=debian TAG=jessie-slim
    # - ADIR=debian TAG=stable
    # - ADIR=debian TAG=stable-slim
    # - ADIR=debian TAG=stretch
    # - ADIR=debian TAG=stretch-slim


    # - ADIR=oraclejdk TAG=8-jre TAGS="8 8u162 8u162-jre" LATEST=y # require debian:stable
    # - ADIR=oraclejdk TAG=8-jre TAGS="8 8u162 8u162-jre" VARIANT=slim # require debian:stable-slim
    # - ADIR=oraclejdk TAG=8-jre TAGS="8 8u162 8u162-jre" VARIANT=alpine # require alpine


    # - ADIR=openjdk TAG=8-jre TAGS="8 8u181 8u181-jre" LATEST=y # require debian:stable
    # - ADIR=openjdk TAG=8-jre TAGS="8 8u181 8u181-jre" VARIANT=slim # require debian:stable-slim
    # - ADIR=openjdk TAG=8-jre TAGS="8 8u171 8u171-jre" VARIANT=alpine # require debian:stable-slim


    # - ADIR=boot-clj TAG=oracle-8-jre  TAGS="oracle-8 oracle-8u162"                 TAG_PREFIX=2.7.2 BUILD_ARGS="--build-arg BOOT_VERSION=2.7.2 --build-arg BOOT_CHECKSUM=f717ef381f2863a4cad47bf0dcc61e923b3d2afb"
    # - ADIR=boot-clj TAG=oracle-8-jre  TAGS="oracle-8 oracle-8u162"  VARIANT=slim   TAG_PREFIX=2.7.2 BUILD_ARGS="--build-arg BOOT_VERSION=2.7.2 --build-arg BOOT_CHECKSUM=f717ef381f2863a4cad47bf0dcc61e923b3d2afb"
    # - ADIR=boot-clj TAG=openjdk-8-jre TAGS="openjdk-8 openjdk-8u162"                TAG_PREFIX=2.7.2 BUILD_ARGS="--build-arg BOOT_VERSION=2.7.2 --build-arg BOOT_CHECKSUM=f717ef381f2863a4cad47bf0dcc61e923b3d2afb"
    # - ADIR=boot-clj TAG=openjdk-8-jre TAGS="openjdk-8 openjdk-8u162" VARIANT=slim   TAG_PREFIX=2.7.2 BUILD_ARGS="--build-arg BOOT_VERSION=2.7.2 --build-arg BOOT_CHECKSUM=f717ef381f2863a4cad47bf0dcc61e923b3d2afb"
    # - ADIR=boot-clj TAG=openjdk-8-jre TAGS="openjdk-8 openjdk-8u151" VARIANT=alpine TAG_PREFIX=2.7.2 BUILD_ARGS="--build-arg BOOT_VERSION=2.7.2 --build-arg BOOT_CHECKSUM=f717ef381f2863a4cad47bf0dcc61e923b3d2afb"


    # - ADIR=lein TAG=oracle-8-jre  TAGS="oracle-8 oracle-8u162"                TAG_PREFIX=2.7.1 BUILD_ARGS="--build-arg LEIN_VERSION=2.7.1"
    # - ADIR=lein TAG=oracle-8-jre  TAGS="oracle-8 oracle-8u162"   VARIANT=slim TAG_PREFIX=2.7.1 BUILD_ARGS="--build-arg LEIN_VERSION=2.7.1"
    # - ADIR=lein TAG=openjdk-8-jre TAGS="openjdk-8 openjdk-8u162"              TAG_PREFIX=2.7.1 BUILD_ARGS="--build-arg LEIN_VERSION=2.7.1"
    # - ADIR=lein TAG=openjdk-8-jre TAGS="openjdk-8 openjdk-8u162" VARIANT=slim TAG_PREFIX=2.7.1 BUILD_ARGS="--build-arg LEIN_VERSION=2.7.1"


    # - ADIR=clojure TAG=openjdk-8-jre HOTTAGS="tools-deps openjdk-8-tools-deps 1.10.1 1.10.1.469" TAGS="openjdk-8 openjdk-8u212 8u212" BUILD_ARGS="--build-arg LINUX_INSTALL_SCRIPT_URL=https://download.clojure.org/install/linux-install-1.10.1.469.sh"
    # - ADIR=clojure TAG=openjdk-8-jre VARIANT=slim HOTTAGS="tools-deps-slim openjdk-8-tools-deps-slim 1.10.0-slim 1.10.1.469-slim" TAGS="openjdk-8 openjdk-8u212 8u212"  BUILD_ARGS="--build-arg LINUX_INSTALL_SCRIPT_URL=https://download.clojure.org/install/linux-install-1.10.1.469.sh"
    # - ADIR=clojure TAG=openjdk-8-jre VARIANT=alpine HOTTAGS="tools-deps-alpine 8-tools-deps-alpine openjdk-8-tools-deps-alpine 1.10.0-alpine 1.10.1.469-alpine" TAGS="openjdk-8 openjdk-8u212 8u212" BUILD_ARGS="--build-arg LINUX_INSTALL_SCRIPT_URL=https://download.clojure.org/install/linux-install-1.10.1.469.sh"
    # - ADIR=clojure TAG=openjdk-11-jre HOTTAGS="11-tools-deps openjdk-11-tools-deps openjdk-11-tools-deps-10.1.469" TAGS="openjdk-11 openjdk-11.0.2 11.0.2" BUILD_ARGS="--build-arg LINUX_INSTALL_SCRIPT_URL=https://download.clojure.org/install/linux-install-1.10.1.469.sh"
    # - ADIR=clojure TAG=openjdk-11-jre VARIANT=slim HOTTAGS="11-slim-tools-deps openjdk-11-slim-tools-deps openjdk-11-slim-tools-deps-10.1.469" TAGS="openjdk-11 openjdk-11.0.2 11.0.2"  BUILD_ARGS="--build-arg LINUX_INSTALL_SCRIPT_URL=https://download.clojure.org/install/linux-install-1.10.1.469.sh"
    # - ADIR=clojure TAG=openjdk-11-jdk HOTTAGS="openjdk-11-jdk-tools-deps openjdk-11-jdk-1.10.0 openjdk-11-jdk-1.10.1.469" TAGS="openjdk-11-jdk 11.0.2-jdk" BUILD_ARGS="--build-arg LINUX_INSTALL_SCRIPT_URL=https://download.clojure.org/install/linux-install-1.10.1.469.sh"
    # - ADIR=clojure TAG=openjdk-11-jdk VARIANT=slim HOTTAGS="openjdk-11-jdk-tools-deps-slim openjdk-11-jdk-1.10.0-slim openjdk-11-jdk-1.10.1.469-slim" TAGS="openjdk-11-jdk 11.0.2-jdk"  BUILD_ARGS="--build-arg LINUX_INSTALL_SCRIPT_URL=https://download.clojure.org/install/linux-install-1.10.1.469.sh"
    # - ADIR=clojure TAG=openjdk-11-jdk VARIANT=oraclelinux7 HOTTAGS="openjdk-11-jdk-tools-deps-oraclelinux7 openjdk-11-jdk-1.10.0-oraclelinux7 openjdk-11-jdk-1.10.1.469-oraclelinux7" TAGS="openjdk-11-jdk 11.0.2-jdk"  BUILD_ARGS="--build-arg LINUX_INSTALL_SCRIPT_URL=https://download.clojure.org/install/linux-install-1.10.1.469.sh"


    # - ADIR=nginx TAG=stable TAGS="1.14.2 1.14"
    # - ADIR=nginx TAG=stable-alpine TAGS="1.14.2-alpine 1.14-alpine"
    # - REPO=ajchemist/nginx DOCKERFILE_PATH=nginx/stable-alpine/brotli TAGS="stable-alpine-brotli 1.14.2-brotli 1.14-brotli"
    # - REPO=ajchemist/nginx DOCKERFILE_PATH=nginx/stable-alpine/dav-ext TAGS="stable-alpine-dav-ext 1.14.2-dav-ext 1.14-dav-ext"


    # - REPO=ajchemist/syslog-ng DOCKERFILE_PATH=syslog-ng TAGS="alpine 3.19.1" LATEST=y


    # - REPO=ajchemist/chromium DOCKERFILE_PATH=chromium/72/alpine TAGS="alpine 72-alpine" LATEST=y
    # - REPO=ajchemist/node DOCKERFILE_PATH=node/lts-alpine/chromium/72 TAGS="lts-alpine-chromium lts-alpine-chromium-72 10.15.3-alpine-chromium 10.15.3-alpine-chromium-72"


.jobs:
  include:
    - stage: another-test
      script:
        - uname -a
        - echo Hello, World


notifications:
  slack:
    rooms:
      - secure: yGzvUZUD8YZ4yPtWth1ynbQ25voXbdKnOnOPSRt59n3aLdSoOt1jVU6ZQUTZ26Eb5hW9z5tqFtrh1tBCJpJkWDGdLJnJRaNa6Si01E17aICxL11uXEK0sahOj3L8/jQIXrSFJKGr75460q33B4aO1l0zGCHsWGL1Kcs+ZqyxeR5afmX4OghpvmyAvHbl9k4ugXdTIbMLwv01qm0HYvJcCzLqU07pY35hN/xPIP1xmt5syFE6jSLfHXKKQk++JcT+JnpMXpmSAuDGBh5fDs6eya5rfx7zuDllooRQ2tXVh1PTyJkfH6ggnPH4U5Tj+ENLseOaWR0emf8cmFAwbUa2Ebg4Z0jM9uaFnKfPw53eIdkQqQq/jlzBuNQ3PwilwdJBYR8X0kVTjDgW2IPLxuiIFW5yPbDG/Ys5rNyhvi92ujjy8pNJzGaZJp8tF4sBxNMB/Ycx1l11CMbAy8q+SJsmAgdXfSFBOj/bgSOd1F97jXhkAOJ9N4bq/0ZeXvVnLRMQ5uZnMuEpsDqBkt+izFl283lnyKcrLXwQ7JDQtAloH5EpXTu40QoJT2k8Y+9MkQSAhlRAQsZuh3BWo+N40Llaeh+YBGMg245r2jgzA7isz9mt6nnrg0DT3RwCC0kbPDn6o7TCnMpceJgqfRyKXE4dnkQYqVrCtj3uIo5TqtCPtWY=
    on_success: always
    on_failure: always
